<?php
/**
 * WebFmMetadataResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  COMPITAUT\DirectAdminAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Swagger DirectAdmin API
 *
 * Swagger API for DirectAdmin server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@directadmin.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace COMPITAUT\DirectAdminAPI\Model;

use \ArrayAccess;
use \COMPITAUT\DirectAdminAPI\ObjectSerializer;

/**
 * WebFmMetadataResponse Class Doc Comment
 *
 * @category Class
 * @package  COMPITAUT\DirectAdminAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WebFmMetadataResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'web.fmMetadataResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'accessTime' => '\DateTime',
        'birthTime' => '\DateTime',
        'changeTime' => '\DateTime',
        'gid' => 'int',
        'group' => 'string',
        'mode' => 'string',
        'modifyTime' => '\DateTime',
        'name' => 'string',
        'sizeBytes' => 'int',
        'symlink' => '\COMPITAUT\DirectAdminAPI\Model\WebFmMetadataSymlink',
        'type' => 'string',
        'uid' => 'int',
        'unixMode' => 'int',
        'user' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'accessTime' => 'date-time',
        'birthTime' => 'date-time',
        'changeTime' => 'date-time',
        'gid' => null,
        'group' => null,
        'mode' => null,
        'modifyTime' => 'date-time',
        'name' => null,
        'sizeBytes' => null,
        'symlink' => null,
        'type' => null,
        'uid' => null,
        'unixMode' => null,
        'user' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'accessTime' => false,
        'birthTime' => false,
        'changeTime' => false,
        'gid' => false,
        'group' => false,
        'mode' => false,
        'modifyTime' => false,
        'name' => false,
        'sizeBytes' => false,
        'symlink' => false,
        'type' => false,
        'uid' => false,
        'unixMode' => false,
        'user' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accessTime' => 'accessTime',
        'birthTime' => 'birthTime',
        'changeTime' => 'changeTime',
        'gid' => 'gid',
        'group' => 'group',
        'mode' => 'mode',
        'modifyTime' => 'modifyTime',
        'name' => 'name',
        'sizeBytes' => 'sizeBytes',
        'symlink' => 'symlink',
        'type' => 'type',
        'uid' => 'uid',
        'unixMode' => 'unixMode',
        'user' => 'user'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accessTime' => 'setAccessTime',
        'birthTime' => 'setBirthTime',
        'changeTime' => 'setChangeTime',
        'gid' => 'setGid',
        'group' => 'setGroup',
        'mode' => 'setMode',
        'modifyTime' => 'setModifyTime',
        'name' => 'setName',
        'sizeBytes' => 'setSizeBytes',
        'symlink' => 'setSymlink',
        'type' => 'setType',
        'uid' => 'setUid',
        'unixMode' => 'setUnixMode',
        'user' => 'setUser'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accessTime' => 'getAccessTime',
        'birthTime' => 'getBirthTime',
        'changeTime' => 'getChangeTime',
        'gid' => 'getGid',
        'group' => 'getGroup',
        'mode' => 'getMode',
        'modifyTime' => 'getModifyTime',
        'name' => 'getName',
        'sizeBytes' => 'getSizeBytes',
        'symlink' => 'getSymlink',
        'type' => 'getType',
        'uid' => 'getUid',
        'unixMode' => 'getUnixMode',
        'user' => 'getUser'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_DIR = 'dir';
    public const TYPE_FILE = 'file';
    public const TYPE_SOCKET = 'socket';
    public const TYPE_SYMLINK = 'symlink';
    public const TYPE_NAMED_PIPE = 'named_pipe';
    public const TYPE_DEVICE = 'device';
    public const TYPE_CHAR_DEVICE = 'char_device';
    public const TYPE_UNKNOWN = 'unknown';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_DIR,
            self::TYPE_FILE,
            self::TYPE_SOCKET,
            self::TYPE_SYMLINK,
            self::TYPE_NAMED_PIPE,
            self::TYPE_DEVICE,
            self::TYPE_CHAR_DEVICE,
            self::TYPE_UNKNOWN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('accessTime', $data ?? [], null);
        $this->setIfExists('birthTime', $data ?? [], null);
        $this->setIfExists('changeTime', $data ?? [], null);
        $this->setIfExists('gid', $data ?? [], null);
        $this->setIfExists('group', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('modifyTime', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('sizeBytes', $data ?? [], null);
        $this->setIfExists('symlink', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('uid', $data ?? [], null);
        $this->setIfExists('unixMode', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['accessTime'] === null) {
            $invalidProperties[] = "'accessTime' can't be null";
        }
        if ($this->container['birthTime'] === null) {
            $invalidProperties[] = "'birthTime' can't be null";
        }
        if ($this->container['changeTime'] === null) {
            $invalidProperties[] = "'changeTime' can't be null";
        }
        if ($this->container['gid'] === null) {
            $invalidProperties[] = "'gid' can't be null";
        }
        if ($this->container['group'] === null) {
            $invalidProperties[] = "'group' can't be null";
        }
        if ($this->container['mode'] === null) {
            $invalidProperties[] = "'mode' can't be null";
        }
        if ($this->container['modifyTime'] === null) {
            $invalidProperties[] = "'modifyTime' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['sizeBytes'] === null) {
            $invalidProperties[] = "'sizeBytes' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['uid'] === null) {
            $invalidProperties[] = "'uid' can't be null";
        }
        if ($this->container['unixMode'] === null) {
            $invalidProperties[] = "'unixMode' can't be null";
        }
        if ($this->container['user'] === null) {
            $invalidProperties[] = "'user' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accessTime
     *
     * @return \DateTime
     */
    public function getAccessTime()
    {
        return $this->container['accessTime'];
    }

    /**
     * Sets accessTime
     *
     * @param \DateTime $accessTime accessTime
     *
     * @return self
     */
    public function setAccessTime($accessTime)
    {
        if (is_null($accessTime)) {
            throw new \InvalidArgumentException('non-nullable accessTime cannot be null');
        }
        $this->container['accessTime'] = $accessTime;

        return $this;
    }

    /**
     * Gets birthTime
     *
     * @return \DateTime
     */
    public function getBirthTime()
    {
        return $this->container['birthTime'];
    }

    /**
     * Sets birthTime
     *
     * @param \DateTime $birthTime birthTime
     *
     * @return self
     */
    public function setBirthTime($birthTime)
    {
        if (is_null($birthTime)) {
            throw new \InvalidArgumentException('non-nullable birthTime cannot be null');
        }
        $this->container['birthTime'] = $birthTime;

        return $this;
    }

    /**
     * Gets changeTime
     *
     * @return \DateTime
     */
    public function getChangeTime()
    {
        return $this->container['changeTime'];
    }

    /**
     * Sets changeTime
     *
     * @param \DateTime $changeTime changeTime
     *
     * @return self
     */
    public function setChangeTime($changeTime)
    {
        if (is_null($changeTime)) {
            throw new \InvalidArgumentException('non-nullable changeTime cannot be null');
        }
        $this->container['changeTime'] = $changeTime;

        return $this;
    }

    /**
     * Gets gid
     *
     * @return int
     */
    public function getGid()
    {
        return $this->container['gid'];
    }

    /**
     * Sets gid
     *
     * @param int $gid gid
     *
     * @return self
     */
    public function setGid($gid)
    {
        if (is_null($gid)) {
            throw new \InvalidArgumentException('non-nullable gid cannot be null');
        }
        $this->container['gid'] = $gid;

        return $this;
    }

    /**
     * Gets group
     *
     * @return string
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param string $group group
     *
     * @return self
     */
    public function setGroup($group)
    {
        if (is_null($group)) {
            throw new \InvalidArgumentException('non-nullable group cannot be null');
        }
        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string $mode mode
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets modifyTime
     *
     * @return \DateTime
     */
    public function getModifyTime()
    {
        return $this->container['modifyTime'];
    }

    /**
     * Sets modifyTime
     *
     * @param \DateTime $modifyTime modifyTime
     *
     * @return self
     */
    public function setModifyTime($modifyTime)
    {
        if (is_null($modifyTime)) {
            throw new \InvalidArgumentException('non-nullable modifyTime cannot be null');
        }
        $this->container['modifyTime'] = $modifyTime;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets sizeBytes
     *
     * @return int
     */
    public function getSizeBytes()
    {
        return $this->container['sizeBytes'];
    }

    /**
     * Sets sizeBytes
     *
     * @param int $sizeBytes sizeBytes
     *
     * @return self
     */
    public function setSizeBytes($sizeBytes)
    {
        if (is_null($sizeBytes)) {
            throw new \InvalidArgumentException('non-nullable sizeBytes cannot be null');
        }
        $this->container['sizeBytes'] = $sizeBytes;

        return $this;
    }

    /**
     * Gets symlink
     *
     * @return \COMPITAUT\DirectAdminAPI\Model\WebFmMetadataSymlink|null
     */
    public function getSymlink()
    {
        return $this->container['symlink'];
    }

    /**
     * Sets symlink
     *
     * @param \COMPITAUT\DirectAdminAPI\Model\WebFmMetadataSymlink|null $symlink symlink
     *
     * @return self
     */
    public function setSymlink($symlink)
    {
        if (is_null($symlink)) {
            throw new \InvalidArgumentException('non-nullable symlink cannot be null');
        }
        $this->container['symlink'] = $symlink;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets uid
     *
     * @return int
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param int $uid uid
     *
     * @return self
     */
    public function setUid($uid)
    {
        if (is_null($uid)) {
            throw new \InvalidArgumentException('non-nullable uid cannot be null');
        }
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets unixMode
     *
     * @return int
     */
    public function getUnixMode()
    {
        return $this->container['unixMode'];
    }

    /**
     * Sets unixMode
     *
     * @param int $unixMode unixMode
     *
     * @return self
     */
    public function setUnixMode($unixMode)
    {
        if (is_null($unixMode)) {
            throw new \InvalidArgumentException('non-nullable unixMode cannot be null');
        }
        $this->container['unixMode'] = $unixMode;

        return $this;
    }

    /**
     * Gets user
     *
     * @return string
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param string $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            throw new \InvalidArgumentException('non-nullable user cannot be null');
        }
        $this->container['user'] = $user;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


