<?php
/**
 * WebDbFullConnectionResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  COMPITAUT\DirectAdminAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Swagger DirectAdmin API
 *
 * Swagger API for DirectAdmin server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@directadmin.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace COMPITAUT\DirectAdminAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WebDbFullConnectionResponseTest Class Doc Comment
 *
 * @category    Class
 * @description WebDbFullConnectionResponse
 * @package     COMPITAUT\DirectAdminAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebDbFullConnectionResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebDbFullConnectionResponse"
     */
    public function testWebDbFullConnectionResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "database"
     */
    public function testPropertyDatabase()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dbuser"
     */
    public function testPropertyDbuser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hostPatterns"
     */
    public function testPropertyHostPatterns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "privileges"
     */
    public function testPropertyPrivileges()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unixSocket"
     */
    public function testPropertyUnixSocket()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
