<?php
/**
 * WebUserUsageTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  COMPITAUT\DirectAdminAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Swagger DirectAdmin API
 *
 * Swagger API for DirectAdmin server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@directadmin.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace COMPITAUT\DirectAdminAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WebUserUsageTest Class Doc Comment
 *
 * @category    Class
 * @description WebUserUsage
 * @package     COMPITAUT\DirectAdminAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebUserUsageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebUserUsage"
     */
    public function testWebUserUsage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "autoresponders"
     */
    public function testPropertyAutoresponders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bandwidthBytes"
     */
    public function testPropertyBandwidthBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dbQuotaBytes"
     */
    public function testPropertyDbQuotaBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domainPointers"
     */
    public function testPropertyDomainPointers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domains"
     */
    public function testPropertyDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailAccounts"
     */
    public function testPropertyEmailAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailDeliveries"
     */
    public function testPropertyEmailDeliveries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailDeliveriesIncoming"
     */
    public function testPropertyEmailDeliveriesIncoming()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailDeliveriesOutgoing"
     */
    public function testPropertyEmailDeliveriesOutgoing()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailForwarders"
     */
    public function testPropertyEmailForwarders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "emailQuotaBytes"
     */
    public function testPropertyEmailQuotaBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ftpAccounts"
     */
    public function testPropertyFtpAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inode"
     */
    public function testPropertyInode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mailingLists"
     */
    public function testPropertyMailingLists()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mySqlDatabases"
     */
    public function testPropertyMySqlDatabases()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "otherQuotaBytes"
     */
    public function testPropertyOtherQuotaBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quotaBytes"
     */
    public function testPropertyQuotaBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quotaWithoutSystemBytes"
     */
    public function testPropertyQuotaWithoutSystemBytes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subdomains"
     */
    public function testPropertySubdomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
