<?php
/**
 * LoginKeysApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  COMPITAUT\DirectAdminAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Swagger DirectAdmin API
 *
 * Swagger API for DirectAdmin server
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@directadmin.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace COMPITAUT\DirectAdminAPI\Test\Api;

use \COMPITAUT\DirectAdminAPI\Configuration;
use \COMPITAUT\DirectAdminAPI\ApiException;
use \COMPITAUT\DirectAdminAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LoginKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  COMPITAUT\DirectAdminAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LoginKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiLoginKeysCommandsGet
     *
     * Get all commands available for login keys.
     *
     */
    public function testApiLoginKeysCommandsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysKeysGet
     *
     * Get all login keys.
     *
     */
    public function testApiLoginKeysKeysGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysKeysIdDelete
     *
     * Delete login key.
     *
     */
    public function testApiLoginKeysKeysIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysKeysIdGet
     *
     * Get login key.
     *
     */
    public function testApiLoginKeysKeysIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysKeysIdHistoryGet
     *
     * Get login key history.
     *
     */
    public function testApiLoginKeysKeysIdHistoryGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysKeysIdPatch
     *
     * Update login key.
     *
     */
    public function testApiLoginKeysKeysIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysKeysPost
     *
     * Create login key.
     *
     */
    public function testApiLoginKeysKeysPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysUrlsGet
     *
     * Get all login URLs.
     *
     */
    public function testApiLoginKeysUrlsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysUrlsIdDelete
     *
     * Delete login URL.
     *
     */
    public function testApiLoginKeysUrlsIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiLoginKeysUrlsPost
     *
     * Create login URL.
     *
     */
    public function testApiLoginKeysUrlsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
